<?php
 
 $title = 'Sửa TermTaxonomy';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
 <a href="<?php echo $this->url('taxonomy/childTaxonomy', array('tax'=>$taxs));?>">Quay lại</a>
 <div class="row">
 <div class="col-lg-6">
 <?php
 //die(var_dump($taxs));
 $form->setAttribute('tax', $this->url('taxonomy/childTaxonomy/crudChildTaxonomy', array('tax'=>$taxs,'action' => 'taxonomyEdit')));
 $form->setAttribute('role','form');
 $form->prepare();

 echo $this->form()->openTag($form);
 $termTaxonomy=$form->get('term-taxonomy');
 $term=$termTaxonomy->get('termId');
 //$term=$termTaxonomy->get('termTaxonomyId');
 echo $this->formHidden($termTaxonomy->get('termTaxonomyId'));
 echo $this->formHidden($term->get('slug'));?>

<div class"form-group">
 <?php $tenTaxonomy=$term->get('name');?>
 <?php $tenTaxonomy->setAttribute('class','form-control'); ?>
 <label><?php echo $tenTaxonomy->getLabel(); ?></label>
 <?php echo $this->formElement($tenTaxonomy);
 	if($coKiemTraTonTai==1)
 	{
 		echo 'Term Taxonomy này đã tồn tại!';
 	} 
?>
</div>

<div>
	<?php $moTaTaxonomy=$termTaxonomy->get('description');?>
	<?php $moTaTaxonomy->setAttribute('class','form-control'); ?>
 	<label><?php echo $moTaTaxonomy->getLabel();?></label>
 	<?php echo $this->formElement($moTaTaxonomy);?>
</div>

<div>
	<?php $parentTaxonomy=$termTaxonomy->get('parent');?>
	<?php $parentTaxonomy->setAttribute('class','form-control'); ?>
 	<label><?php echo $parentTaxonomy->getLabel();?></label>
 	<?php
 		  $parentTaxonomy->setValueOptions($this->makeArrayCollection($termTaxonomys)); 
 	?>
 	<?php echo $this->formElement($parentTaxonomy);?>

</div>
 
 <?php 
 $submit=$form->get('submit');
 $submit->setValue('Sửa');
 echo $this->formSubmit($submit);
 echo $this->form()->closeTag();?>

</div>
</div>