<?php 
//use BaconStringUtils\Slugifier;
//use BaconStringUtils\UniDecoder;
?>
<SCRIPT LANGUAGE="JavaScript">
    function confirmAction() {
      var xacNhan=confirm("Nếu xóa term taxonomy này thì các taxonomy cấp con của nó sẽ bị xóa. Bạn thật sự muốn xóa TermTaxonomy này?");
      if(xacNhan==true)
      {
        return true;
      }
      return false;
    }
</SCRIPT>
<?php
 foreach ($termTaxonomys as $termTaxonomy)
 {
    if(!$termTaxonomy->getParent())
    {
        $ten=$termTaxonomy->getTermId()->getName();
        $tax=$termTaxonomy->getTermId()->getSlug();

    }
 }

 $title = 'Quản lý Taxonomy '.$ten;
 $this->headTitle($title); 
 ?> 
 <h1><?php echo $this->escapeHtml($title); ?></h1> 
 <a href="<?php echo $this->url('s3u_taxonomy');?>">Quay lại</a>
 <?php
 $t=$termTaxonomys[0]->getTaxonomy();
 //var_dump($t);
 //die(var_dump($termTaxonomys));
 ?>
 <p>        
     <a href="<?php echo $this->url('taxonomy/childTaxonomy/crudChildTaxonomy', array('tax'=>$t,'action'=>'taxonomyAdd'));?>">Thêm Taxonomy con</a>
 </p>
<form method="post">
 <table class="table">
 <tr>
     
     
     <th>Term</th>
     <th>Slug</th>
     <th>Description</th>     
     <th>Sửa</th>
     <th>Xóa</th>
 </tr> 

<?php  foreach ($termTaxonomys as $termTaxonomy):
            if($termTaxonomy->getParent())
            {
?>
 <tr>
     
     <td>
     	<?php echo str_repeat("&#8212;&#8212;&#8212;&#8212; ", $termTaxonomy->getCap()).$this->escapeHtml($termTaxonomy->getTermId()->getName());?>
     </td>
     <td>
        <?php echo $this->escapeHtml($termTaxonomy->getTermId()->getSlug());?>
     </td>
     <td>
     	<?php echo $this->escapeHtml($termTaxonomy->getDescription());?>
     </td>
     
     <td>
         <a href="<?php echo $this->url('taxonomy/childTaxonomy/crudChildTaxonomy',
             array('tax'=>$tax, 'action'=>'taxonomyEdit', 'id' => $termTaxonomy->getTermTaxonomyId()));?>">Sửa</a>         
     </td>   
     <td>
         
         <a href="<?php echo $this->url('taxonomy/childTaxonomy/crudChildTaxonomy',
             array('tax'=>$tax, 'action'=>'taxonomyDelete','id'=>$termTaxonomy->getTermTaxonomyId()));?>" onclick="return confirmAction()">Xóa</a>
     </td>    
 </tr>
 <?php 
        }
    endforeach;
 ?> 
 </table>
</form>
