<?php
 
 $title = 'Thêm taxonomy con';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
 <div class="row">
 <div class="col-lg-6">
 <?php
 //die(var_dump($taxs));
 $form->setAttribute('tax', $this->url('taxonomy/childTaxonomy/crudChildTaxonomy', array('tax'=>$taxs,'action' => 'taxonomyAdd')));
 $form->setAttribute('role','form');
 $form->prepare();

 echo $this->form()->openTag($form);
 echo $this->formHidden($form->get('term_taxonomy_id'));?>

<div class"form-group">
 <?php $tenTaxonomy=$form->get('taxonomy');?>
 <?php $tenTaxonomy->setAttribute('class','form-control'); ?>
 <label><?php echo $tenTaxonomy->getLabel(); ?></label>
 <?php echo $this->formElement($tenTaxonomy); 
if($checkTermTaxonomy==0)
 {
	echo 'Taxonomy bạn vừa thêm đã tồn tại';
 }
?>
</div>
<div>
	<?php $moTaTaxonomy=$form->get('description');?>
	<?php $moTaTaxonomy->setAttribute('class','form-control'); ?>
 	<label><?php echo $moTaTaxonomy->getLabel();?></label>
 	<?php echo $this->formElement($moTaTaxonomy);?>
</div>
 
 <?php 
 $submit=$form->get('submit');
 $submit->setValue('Thêm');
 echo $this->formSubmit($submit);
 echo $this->form()->closeTag();?>

</div>
</div>