<?php

 $title = 'Thêm taxonomy';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
 <div class="row">
 <div class="col-lg-6">
 <?php
 $form->setAttribute('action', $this->url('s3u_taxonomy/crud', array('action' => 'add')));
 $form->setAttribute('role','form');
 $form->prepare();

 echo $this->form()->openTag($form);
 echo $this->formHidden($form->get('term_taxonomy_id'));?>

<div class"form-group">
 <?php $tenTaxonomy=$form->get('taxonomy');?>
 <?php $tenTaxonomy->setAttribute('class','form-control'); ?>
 <label><?php echo $tenTaxonomy->getLabel(); ?></label>
 <?php echo $this->formElement($tenTaxonomy); ?>
</div>
 
 <?php 
 $submit=$form->get('submit');
 $submit->setValue('Thêm');
 echo $this->formSubmit($submit);
 echo $this->form()->closeTag();?>

</div>
</div>