<?php 

 $title = 'Sửa';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>

 <?php
 $form = $this->form;
 $form->setAttribute('action', $this->url(
     's3u_taxonomy/crud',
     array(
         'action' => 'edit',
         'id'     => $this->id,
     )
 ));
 $form->prepare();

 echo $this->form()->openTag($form);
 echo $this->formHidden($form->get('term_taxonomy_id')); 
 echo $this->formRow($form->get('taxonomy')); 

 echo $this->formSubmit($form->get('submit'));
 if($this->co==0)
 {
 	echo '<br>Đã tồn tại';
 }
 echo $this->form()->closeTag();