<?php

 $title = 'Quản lý Taxonomy';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
 <p>
     <a href="<?php echo $this->url('s3u_taxonomy/crud', array('action'=>'add'));?>">Thêm Taxonomy</a>
 </p>
<form method="post">
 <table class="table">
 <tr>
     
     <th>Taxonomy</th>
     <th>Sửa</th>
     <th>Xóa</th>
 </tr> 
 <?php foreach ($zfTermTaxonomys as $zfTermTaxonomy):?>
 <tr>     
     <td><?php echo $this->escapeHtml($zfTermTaxonomy->getTaxonomy());?></td>
     <td>
         <a href="<?php echo $this->url('s3u_taxonomy/crud',
             array('action'=>'edit', 'id' => $zfTermTaxonomy->getTermTaxonomyId()));?>">Sửa</a>         
     </td>   
     <td>
         
         <a href="<?php echo $this->url('s3u_taxonomy/crud',
             array('action'=>'delete', 'id' => $zfTermTaxonomy->getTermTaxonomyId()));?>">Xóa</a>
     </td>    
 </tr>
 <?php endforeach; ?> 
 </table>
</form>
